// <auto-generated />
using InvoiceGeneratorAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceGeneratorAPI.Migrations
{
    [DbContext(typeof(InvoiceTemplateContext))]
    [Migration("20231025035130_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceGeneratorAPI.Models.InvoiceTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TemplateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyEmailCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNameCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPOBoxCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPhoneCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerAddressCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNameCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceDateCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceIdCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceTotalCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemIdCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemPriceCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemPriceTotalCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemQuantityCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemSizeCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipDateCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipeeAddressCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipeeNameCell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplatePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumberCell")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dbo.InvoiceTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
